### ISSUE TITLE
Multiple monitor windows

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#10]
I can't drag the window fully from my laptop to my external monitor; it keeps resetting half a screen lower every time I try to drag up.  Trying to full screen the app puts it halfway on each screen.  I can get it to the top of the external monitor by a dance of "resize small" then "drag up" and then "resize bigger".

**Comment by ennerf** [comment]
switched to the OS-supplied window border, so the behavior should be identical to 'old' Scope. Please re-open if this is still an issue.

**Comment by iamtesch** [comment]
works now.
