### ISSUE TITLE
Small values get rounded to zero when loading from XML

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#107]
If values are small in an XML file, I think less than 0.001, they get rounded to 0 in the field in Scope before setting.  You can type the small value in manually in Scope and it works, this is just something that happens when loading from XML.

**Comment by ennerf** [comment]
Each field specifies a format for the feedback, e.g., `#0.###` for 3 digits. The same format is also used when loading xml files, so you don't get `10/3 = 3.33333333333333333333` with 17 digits.

I assume input equations happen little enough that I can just get rid of the feature? That'd get rid of accidentally cutting off input values.
