### ISSUE TITLE
Imitiation Groups on localhost don't show on MacOS.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#109]
This is on Ventura 13.3.

Selecting 'Any' works, and the modules all show up on the network as expected.  But when selecting 'Localhost' I'm unable to see any modules.

**Comment by ennerf** [comment]
The next snapshot will include a notification that localhost lookup is not enabled by default. After a user acknowledges, the notification will not be shown again until the next start.

![image](https://github.com/HebiRobotics/hebi-scope-feedback/assets/5491587/4e0412e2-cd67-44e9-802a-8d2f43487e29)
