### ISSUE TITLE
Imitation Groups: MAC addresses not unique, even across different systems

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#113]
The reported MAC address of the imitation group modules are identical, even if you create an imitation group on system A and system B through scope.  This leads to some problems during group lookup in C/C++/Python, where we assume unique mac + subaddress constraints across the created group.

**Comment by ennerf** [comment]
For imitation it wasn't accessing the real interfaces at all (only for the embedded devices, but there are edge cases w/ retries etc. and it's not necessary), so it was just derived from `0x02 + <ip>`. However, the IP was also a static default value of `127.0.0.1`, so every mac was 02:00:7F:00:00:01.

Fixed to be `0x02 + <random-int>`. Nothing depends on these values to be meaningful.
