### ISSUE TITLE
Show App Version somewhere in App

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#17]
It would be nice to be able to tell what version you're running.  Maybe on the Window pane?

**Comment by ennerf** [comment]
![image](https://user-images.githubusercontent.com/5491587/47294598-dcac5300-d60d-11e8-96d8-29f31ec55872.png)

Added to title bar. May be better in top/left corner, but for now that should be visible enough.

**Comment by daverolli** [comment]
FWIW I looked all over the place in MacOS and Windows, and didn't notice it was in the title bar until I looked up the issue.
