### ISSUE TITLE
Highlight Gain changes on hidden (advanced) fields

### ISSUE THREAD

**Issue by ennerf** [HebiRobotics/scope2-feedback#3]
The "Advanced" toggle should be highlighted yellow if any of the hidden fields have changed. 

Send doesn't send hidden fields, but it'd be good indicator that there has been some change from e.g. default gains.

**Comment by daverolli** [comment]
Nice.  The 'Send' and 'Show Advanced' sliders are highlighted if there's a change on the 'Advanced' and the the 'Send' is lit if the change is on the standard panel.  Confirmed working on macOS and Windows.
