### ISSUE TITLE
Cannot drag any part of window past the screen edge

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#31]
Tested: Ubuntu 16.04

I can drag around and resize the main scope window, but cannot drag it so that some of it "hangs off" the screen.  The full extent of the UI always must be contained within the boundaries of the screen.

**Comment by ennerf** [comment]
![image](https://user-images.githubusercontent.com/5491587/47293898-c3a2a280-d60b-11e8-9262-58fff82a61f7.png)

Can't reproduce. Is this still an issue after the change to the default system border?

**Comment by iamtesch** [comment]
works for me now.
