### ISSUE TITLE
When closing a plot window, the button of the last-clicked plot gets highlighted.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#34]

**Comment by daverolli** [comment]
Happens in Windows 10 Pro and macOS Mojave.

**Comment by ennerf** [comment]
Which OS ? Can't reproduce on Windows.

**Comment by daverolli** [comment]
When selecting multiple modules and plotting the button doesn't highlight until you close the last plot window.  Again same behavior on Mac / Windows.

**Comment by ennerf** [comment]
Thanks. Fixed.
