### ISSUE TITLE
Reduce time to open the first plot

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#35]
In macOS when clicking a plot button for the first time there is a ~2 second hang before the plot pops up.  There is no animation from the mouse-click so it looks like the app is hanging.  It was long enough for the OSU guys to notice when doing a live demo.  

On windows the stutter is much shorter, and there's a partial animation that makes it clear the click was received.

**Comment by ennerf** [comment]
Future note: There is also a ~2 second hang the first time someone enters a bad value into a text field, e.g., gains. Pre-Initializing without rendering didn't work, and initializing while rendering added 2 seconds to the startup, which was even worse.

**Comment by ennerf** [comment]
This is an issue for Linux as well. May be related to initializing the communications?

**Comment by ennerf** [comment]
Solved in 1.6.4
