### ISSUE TITLE
Developer signing / Connection warning on startup

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#36]
On macOS there is a warning dialog that pops up every time asking if you want the app to allow incoming connections.  I've tried adding the app to the 'allowed apps' section in Firewall Settings, but this still persists.  

I'm assuming this is also tied to another issue where after downloading you can't double-click to open the app in macOS.  Instead you have to right-click, open, then click thru a warning dialog saying this app isn't from a trusted developer.

**Comment by ennerf** [comment]
I've looked at this a bit before. Below are some notes for my own future reference:

There are two different types of `Code Signing Certificates` for Windows. We'd need the `OV`. Some certificates seem to also support other operating systems. Below are some certified vendors that sell them (see also [Microsoft](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate#span-idstep2buyanewcodesigningcertificatespanspan-idstep2buyanewcodesigningcertificatespanspan-idstep2buyanewcodesigningcertificatespanstep-2-buy-a-new-code-signing-certificate))

* [Symantec](https://products.websecurity.symantec.com/orders/enrollment/winqualOrder.do)
* [Certum](https://en.sklep.certum.pl/data-safety/code-signing-certificates/standard-code-signing.html)
* [Entrust](https://www.entrustdatacard.com/products/categories/digital-signing-certificates/compare-entrust-code-signing-certificates)
* [InstantSSL](https://www.instantssl.com/ssl-certificate-products/code-signing-index.html)
* [digicert](https://www.digicert.com/order/order-1.php)

Other than the fact that I didn't have time yet, one reason that I am hesitating a bit is that we would have to sign the executable, i.e., the Java runtime, but the actual `jar file` (our code) is unsigned. That would theoretically allow anyone to download Scope, replace the jar file, and execute arbitrary Java code using our company certificate.

**Comment by ennerf** [comment]
Done.
