### ISSUE TITLE
Have buttons at the top of gains tab stay visible when scrolling down.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#39]
When the advanced gains are shown, the screen is a bit too much to fit on a laptop monitor.  So when you're adjusting things like lowpass at the bottom of the list you have scroll back up to click 'send'.  On Scope <0.13 things were just tight enough to fit without scrolling.

**Comment by daverolli** [comment]
Don't think this is really necessary on the other tabs.  Gains is the only one where the typical workflow is 'something at the bottom' then 'something at the top'.

**Comment by ennerf** [comment]
That sounds like a good idea

Additional thought, do you want a keyboard shortcut for `send` ?

**Comment by daverolli** [comment]
oooh.  A keyboard shortcut might be nice.

**Comment by ennerf** [comment]
what key combo do you want it to be?

**Comment by daverolli** [comment]
Maybe cmd+S?  That might be a bit weird.  

Maybe cmd+F/G/H?

**Comment by ennerf** [comment]
How about:

* `ctrl+s` -> save
* `ctrl+d` -> clear
* `ctrl+f` -> send
* `ctrl+g` -> load default gains

**Comment by ennerf** [comment]
Jan made buttons stable. I'll create a separate issue for the key combos

**Comment by daverolli** [comment]
Yup.  Buttons are stable at the top on macOS and Windows
