### ISSUE TITLE
File name for packaged macOS version says OSX.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#40]
Really minor, but just wanted to make a note of it.

**Comment by ennerf** [comment]
I thought OSX was correct. Should it be hebi-scope-1.0-macOS64 ?

**Comment by daverolli** [comment]
Yup.  It should be just be macOS.  You can put the 64, but 32-bit support gets dropped next year.

**Comment by ennerf** [comment]
released
