### ISSUE TITLE
Save or convert log files to formats other than .hebilog, particularly CSV.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#42]
Scope currently only saves `.hebilog` files, which can be loaded in APIs, but isn't compatible with other tools.  CSV conversion would a good addition and would hit all spreadsheet/plotting tools like GSheets / Excel.

**Comment by ennerf** [comment]
We were planning on making a separate tool that can work with log files and provide plots and conversions to various formats. Should this be part of Scope instead?

**Comment by rLinks234** [comment]
Honestly, I'd be inclined to say that we should add this to our APIs
