### ISSUE TITLE
Effort slider immediately commands full PWM when selected in DIRECT_PWM

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#47]
If you have a module in `DIRECT_PWM` control strategy, checking box to enable the Effort slider immediately commands a PWM of 1.  Once you drag the slider, things work correctly.

**Comment by ennerf** [comment]
The slider got updated to effort fbk, and on `DIRECT_PWM` it stopped updating. I changed it to move the slider to zero after switching.

**Comment by ennerf** [comment]
Released in 1.1
