### ISSUE TITLE
Permanent hang in macOS when closing multiple windows

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#50]
In macOS, if you open multiple plotting windows at once (plotting when modules are multi-selected), and you don't put each one of them into front focus, hitting 'Close All' causes Scope to hang until you force-quit.   If you click on each plotting window so that all of them see front focus at least once this doesn't happen.  If you close the plot windows one at a time, either with the mouse or with `Cmd+W`, this doesn't happen.

For example if I select 4 modules, click around or move 3 of the windows, but never touch the 4th, the app will hang when I click 'Close-All'.  This happens a lot because I usually open a bunch of plot windows, realize I have the PPI setting wrong, then click 'Close All' to try to fix.

**Comment by ennerf** [comment]
Issue may be fixed in latest snapshot. Please try again.

**Comment by daverolli** [comment]
Problem is still there.  No change.  FWIW I was running from the .jar file since the macOS packaged version wasn't built.

**Comment by daverolli** [comment]
Problem still occurs in macOS in latest 1.5-SNAPSHOT.

**Comment by ennerf** [comment]
Found solution in https://stackoverflow.com/a/27827033. Fixed it on my test mac
