### ISSUE TITLE
IP Address is cleared when you select "static" by accident

### ISSUE THREAD

**Issue by curtishebi** [HebiRobotics/scope2-feedback#51]
IP Address Field does not re-populate if you click "Static" and then go back to "DHCP" without changing the address it clears the address in the firmware. It would be great if there was a "Set" button for this.

**Comment by ennerf** [comment]
I noticed that as well :( That happens because the firmware reports 0.0.0.0 after setting DHCP mode, so that may require a firmware change.

**Comment by ennerf** [comment]
This feature was removed, so it doesn't apply anymore
