### ISSUE TITLE
Lower default range of position slider

### ISSUE THREAD

**Issue by ennerf** [HebiRobotics/scope2-feedback#57]
At the moment it defaults to +/- 4 rotations, which matches the absolute multi-turn encoding. However, this doesn't make sense for a lot of kits, so we may want to lower the default range.

Now that we have safety limits, we may also want to base the sliders off of those rather than the gains. Maybe first check safety limits, then gains, then defaults?

**Comment by daverolli** [comment]
I think going off of limits / then gains / then fallback defaults is a good idea.

**Comment by ennerf** [comment]
Added it and reduced default positon range to +/- 2 rotations
