### ISSUE TITLE
Re-arrange buttons on Monitoring Tab

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#58]
The old layout of buttons for plotting was a little more intuitive.  In particular Position/Velocity/Effort buttons were grouped vertically, Gyro/Accel were paired vertically, Voltage/Current were paired vertically.

**Comment by ennerf** [comment]
changed layout to

![image](https://user-images.githubusercontent.com/5491587/49163431-592d0280-f32d-11e8-9fc5-7a30df59567d.png)

**Comment by ennerf** [comment]
I could go either way on switching PWM and Temperature, but I think this way fits a bit better visually
