### ISSUE TITLE
Plots always start with 'auto' time scale on restart.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#60]
We added the feature to remember the `PPI` and `Time` settings and use them the next time Scope gets restarted.  The values in the drop-downs fill in correctly, and the PPI does set correctly, but the plots still start up in `Auto` mode.  Switching to another value for `Time` in the drop-down sets correctly.

**Comment by ennerf** [comment]
Thanks. Fixed it.
