### ISSUE TITLE
Renaming Family and Name

### ISSUE THREAD

**Issue by ethanschumannHEBI** [HebiRobotics/scope2-feedback#63]
Renaming the family and name without pressing enter doesn't actually send the new family and name to the module. Possibly have it send after the user clicks out of the text box or have it revert back to the previous name.

**Comment by daverolli** [comment]
Or maybe have some sort of prompt or mouse-over that explains that you need to hit enter?  Not sure.

**Comment by ennerf** [comment]
Removed functionality for now
