### ISSUE TITLE
Text fields don't reset or send information on cancel

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#66]
When you edit the name (or family) in the text boxes in the dashboard/monitoring/etc pages, and then click outside the box, the name doesn't get set on the module _or_ reset the text box.  Navigating to a different tab changes the text back to its original value, but only on the new tab -- if you go back to the original tab, it is still changed with the edited text.  This state remains even if you interact with other items on the page (e.g., the other text boxes).  The expected behavior for me would be for the change to either take effect or get cancelled as soon as you click outside that text field.  Right now this only appears to happen if "Enter" is pressed ("Esc", "Tab", or clicking elsewhere have no effect)

**Comment by ennerf** [comment]
removed renaming functionality via text fields
