### ISSUE TITLE
Scope startup speed - splash screen

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#67]
It can take a long time (>4 or 5 seconds) for Scope to start up, and I (and others) frequently start Scope up twice after waiting and thinking we didn't click correctly.

As a workaround, I wondered if it might be possible to have a splash screen quickly pop up to prevent the perception that the app is not starting?

**Comment by ennerf** [comment]
This may work https://stackoverflow.com/a/39132763
