### ISSUE TITLE
Full screen behavior on Linux

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#7]
If you full-screen the app on Ubuntu (at least 16.04 on Matt's machine), dragging the "HEBI Scope" title bar at the top of the page will instead move another window (it moved both MATLAB and Firefox for me in testing)

**Comment by ennerf** [comment]
switched to the OS-supplied window border, so the behavior should be identical to 'old' Scope. Please re-open if this is still an issue.

**Comment by iamtesch** [comment]
confirmed -- this works!
