### ISSUE TITLE
Provide some example custom plots with packaged Scope

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#72]
It might be nice to have a couple examples of some custom plots to get people started.

**Comment by ennerf** [comment]
There are examples for the xml content on the docs page. Do you want to add links to make them downloadable as xml files, or are you referring to shipping Scope with example custom plots?

![image](https://user-images.githubusercontent.com/5491587/56948343-28493780-6b30-11e9-8393-54b8a53099d4.png)

**Comment by ennerf** [comment]
Sorry, didn't realize it was in the title. Do you have any specific plots in mind?

**Comment by ennerf** [comment]
added to `1.4`
