### ISSUE TITLE
Scope - persist buttons + toggles

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#75]
Issues that came up from customer feedback today
- [x] The "persist" button on the dashboard should probably be removed; it is unintuitive because there is nothing on this pane which doesn't already persist when it is set
- [x] The 'persist sends' toggle state should probably not be saved between reboots.  This makes it easy to accidentally persist sends the next time you have the GUI open, especially if you just toggled this as you were initially exploring the GUI.

**Comment by ennerf** [comment]
Removed the persist button from Dashboard. The idea was that users should be able to persist without having to go to Gains and send a dummy message with the persist flag on. Considering that (1) many things auto-persist now, and (2) we are moving away from persisted gains towards loading them each run I think removing it makes sense

**Comment by ennerf** [comment]
Removed persisting behavior from the dashboard and monitoring toggle
