### ISSUE TITLE
Make "set position/effort" pane in dashboard much more dangerous looking

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#76]
Issues that came up from customer feedback today

It is easy to change the user offset of the module when exploring the GUI, and not realizing the effect it has.

Some ideas:
- When toggled, potentially have a warning dialog.
- Have a background on the pane that is red or orange. 
- Have a "warning" icon on the pane
- Have an "are you sure" dialog _every time_ you press "send" for the user offset / torque

**Comment by ennerf** [comment]
* added "are you sure" dialog
