### ISSUE TITLE
[Linux] Module discovery

### ISSUE THREAD

**Issue by Giggus** [HebiRobotics/scope2-feedback#85]
Hi, 

I just received my new pc with Ubuntu 18.04. 
My java version is openjdk 11.0.4. 

When I plug the robot on the network I can find all hebi modules with my old laptop but, with the new one, I can only ping them but not visualize them on the Scope.

I also tried the old 1.14 Scope version but I still don't see hebi motors.

Can you please help me with this?

**Comment by ennerf** [comment]
Hi,

Scope is not compatible with OpenJDK 11 due to some backwards incompatible changes in Java 9, and because it requires JavaFX / OpenJFX.

Please try the standalone version from our [docs page](http://docs.hebi.us/downloads_changelogs.html). It includes an appropriate runtime with all dependencies.

![image](https://user-images.githubusercontent.com/5491587/62767529-31359780-ba95-11e9-8391-697afc79d0cf.png)

**Comment by ennerf** [comment]
I just saw that the documentation was incorrect.

![image](https://user-images.githubusercontent.com/5491587/62767826-c9cc1780-ba95-11e9-8d94-7b67e848667e.png)

I have updated it to the following:

![image](https://user-images.githubusercontent.com/5491587/62767871-e10b0500-ba95-11e9-88ea-2cde544abb8b.png)

**Comment by Giggus** [comment]
that at least explains why ! Thanks for the reply.. I'll use another laptop for the moment.

**Comment by Giggus** [comment]
I actually tried with another Ubuntu 18.04 which has Java 11 and it does work.
I am wondering why on the other platform it doesn't. Are there any other dependencies?

**Comment by rLinks234** [comment]
@Giggus , have you done any modifications to your firewall configuration? Even if not, that may still be the issue.

---

Assuming you didn't customize your Ubuntu 18.04 install:

Try disabling your firewall (temporarily) in a console by doing

```sh
sudo ufw disable
```

Make sure to re-enable `ufw` after testing in Scope! (`sudo ufw enable`)

---

If this allows you to see the modules in Scope, then you will need to add a firewall rule to allow traffic from our APIs and Scope:

```sh
sudo ufw allow 16665/udp
```

**Comment by Giggus** [comment]
> @Giggus , have you done any modifications to your firewall configuration? Even if not, that may still be the issue.
> 
> Assuming you didn't customize your Ubuntu 18.04 install:
> 
> Try disabling your firewall (temporarily) in a console by doing
> 
> ```shell
> sudo ufw disable
> ```
> 
> Make sure to re-enable `ufw` after testing in Scope! (`sudo ufw enable`)
> 
> If this allows you to see the modules in Scope, then you will need to add a firewall rule to allow traffic from our APIs and Scope:
> 
> ```shell
> sudo ufw allow 16665/udp
> ```

It actually works if I disable the firewall!! But the `sudo ufw allow 16665/udp` doesn't make the job once I re-enable the firewall. 

To avoid to disable the firewall do you have any others idea to allow the connection with Scope and HEBI motors?

Thanks!

**Comment by rLinks234** [comment]
I believe that there are additional firewall rules to add to what I mentioned above, @Giggus . It basically comes down to the fact that module discovery requires sending out broadcast packets to the modules.

EDIT: I typed out a message which was incorrect. I will respond with a (valid) workaround shortly

**Comment by rLinks234** [comment]
@Giggus , I apologize for the delay. Try adding these rules to `ufw` and let me know if it resolves your issues:

```sh
sudo ufw allow proto udp from <ETH_SUBNET> to any port 16665
sudo ufw allow proto udp out 16665
```

---

Above, you can determine each `ETH_SUBNET` (you may have more than one if you have multiple ethernet cables/networks on your workstation) by executing `ip a` in a terminal. For example,

```
>>> ip a

... Other interfaces ...

2: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.xxx/24 brd 10.10.10.255 scope global dynamic noprefixroute enp0s31f6
       valid_lft xxxxxsec preferred_lft xxxxxsec
    inet6 xxxx::xxxx:xxxx:xxx:xxxx/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

... Other interfaces ...

```

`ETH_SUBNET` from above would be `10.10.10.0/24`. Most subnets are in the `192.168.x.x` and `10.x.x.x` range, _e.g._:

`10.10.10.0`
`10.10.1.0`
`10.10.2.0`
`192.168.1.0`
`192.168.10.0`

---

Let me know if you have any additional issues.

**Comment by ennerf** [comment]
Given that there has been no response I assume that this issue has been resolved.
