### ISSUE TITLE
Top Navigation Bars sometimes getting hidden.

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#86]
Scope, title bar sometimes got buried
- Shrink screen so you have to scroll 
- Go to gains tab
- Change a value.
- When buttons highlight in yellow, the nav tabs at the top get buried.

Reproducible in Windows and macOS

**Comment by daverolli** [comment]
Settings button in lower-left also got buried at one point, with no ability to get it back.  Not sure how to reproduce though.  It was happening on a Dell laptop with somewhat lo-res screen running Windows.

**Comment by daverolli** [comment]
Looks like the lower-left issue comes from the same 'enter a gains value' error that can bury the top menu.  Reproducible in Windows and macOS.

**Comment by ennerf** [comment]
this was an issue with the validation library and was fixed
