### ISSUE TITLE
Zooming issues in new plots (Scope 1.6)

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#89]
When zooming in with the default drag-to-zoom more than once, an extra dashed line shows up after the second zoom.

When zooming in with the default drag-to-zoom more than once, the scale on the side does not update after the first zoom.

There also always seems to be a dashed line hidden at the bottom of the plot.  For example, when sending commands and that stopping, instead of disappearing the line shoots to the bottom.

**Comment by ennerf** [comment]
Could you make screenshots?

**Comment by daverolli** [comment]
https://www.dropbox.com/s/trvranyamissx4k/Scope1.6_PlottingIssues.mov?dl=0

Same issues on Windows.
