### ISSUE TITLE
Dashed lines are not getting rendered correctly (Scope 1.6)

### ISSUE THREAD

**Issue by ennerf** [HebiRobotics/scope2-feedback#90]
Dashed lines works when points are relatively far away (e.g. fast movements), but they look like a solid line when points are too close to each other.

![image](https://user-images.githubusercontent.com/5491587/68352552-bcc8ce00-0141-11ea-90fa-57f37f627b62.png)

**Comment by RalphSteinhagen** [comment]
Commit GSI-CS-CO/chart-fx@b45abf7 addresses [Scope #90](https://github.com/HebiRobotics/hebi-scope-feedback/issues/90) and statements like `dataSet1.setStyle("strokeDashPattern= 25, 20, 5, 20;");`being now being correctly passed through to JavaFX's `GraphicsContext` rendering pipe-line.

**Comment by RalphSteinhagen** [comment]
A small chart-fx example illustrating a (here deliberately exaggerated) '100-pixel dash, 100-pixel gap' dashed polyline over 1e6 points. The new algorithm draws dashes (when defined) acrossthe individual points and restarts only when NaN values are encountered. 

![image](https://user-images.githubusercontent.com/46007894/68364305-d4965700-012d-11ea-801f-755fdea8ac90.png)

N.B. the blue curve has still the error contour surface enabled. Enjoy!

**Comment by ennerf** [comment]
Thanks!
