### ISSUE TITLE
LogViewer does not switch between charts when zoomed in

### ISSUE THREAD

**Issue by ennerf** [HebiRobotics/scope2-feedback#91]
* Select device + chart
* Zoom into chart
* Select different chart or device

**What is supposed to happen**
switch viewing area

**What happens**
nothing

**Comment by rLinks234** [comment]
I noticed this too on Linux - sorry I forgot to mention it or file a bug.

**Comment by ennerf** [comment]
This was a bug in chart-fx and got fixed in 11.1.2. See https://github.com/GSI-CS-CO/chart-fx/issues/78
