### ISSUE TITLE
Load Defaults - Error Window [Linux v1.6.1]

### ISSUE THREAD

**Issue by josephcoombe** [HebiRobotics/scope2-feedback#92]
Running Scope v1.6.1 on Ubuntu Ubuntu 18.04.4 LTS (HEBI Square Chassis).

Connected to internet via USB-to-Ethernet adapter (which I'm using to write this issue).

In the Gains tab, left-clicking **Load Defaults** produces this Error Window
![Screenshot from 2020-03-30 17-31-05](https://user-images.githubusercontent.com/12258096/77968496-18405780-72ad-11ea-965f-4fbb8c0d34b2.png)

**Comment by ennerf** [comment]
Thanks for reporting this.

The files ultimately come from [https://docs.hebi.us/resources/gains/](https://docs.hebi.us/resources/gains/), which was recently changed to only accept `https`. The server has been updated and everything should be working again.
