### ISSUE TITLE
convert log file button state

### ISSUE THREAD

**Issue by iamtesch** [HebiRobotics/scope2-feedback#93]
The "save as" button doesn't always show up when converting logs.

Repro:
- press convert log button
- select log to convert
- change "view" to one of the right two buttons (e.g., not "full")
- change "format" to "csv"; the "save as" disappears.
- change "view" to the left button; "save as" is not reenabled.

You can change format back to "mat" and then "csv" to resolve, but ideally the "view" selection would automatically be set to the supported mode when selecting "csv", or at least re-enabled when selecting "full".

**Comment by ennerf** [comment]
Thanks for reporting this. Will be fixed next snapshot.
