### ISSUE TITLE
custom charts : change reset icon

### ISSUE THREAD

**Issue by ennerf** [HebiRobotics/scope2-feedback#96]
The garbage looks scary. We should switch to the reload or circular-back-arrow symbols

**Comment by daverolli** [comment]
![OscartheGrouch](https://user-images.githubusercontent.com/5423160/133819311-a826d337-777a-4d02-bd89-39ecc0bf9720.jpg)

**Comment by ennerf** [comment]
![image](https://user-images.githubusercontent.com/5491587/134324289-9c74eacc-d327-402b-b834-e1220c36e01b.png)

:+1:
