### ISSUE TITLE
On plots, provide a buffer to readings that are near min / max

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#98]
Maybe just a 5% - 10% buffer of full scale would work.  That makes it easier to zoom in and see details in context.

**Comment by ennerf** [comment]
It should already be doing that. Can you provide more info on where you are encountering problems?

![image](https://user-images.githubusercontent.com/5491587/134319209-247958bf-81a1-44b8-acab-31357485bbe1.png)

**Comment by daverolli** [comment]
To me, the bottom and top plots above both show the issue. 

 The bottom is readings of the bottom plot are really close to the line.  The top plot gets so close to the top that the hidden ‘zoom’ tools pop down.  
 
I guess what I’m asking for is a bigger buffer?  Or maybe have it based on a percentage of full scale range if it’s not already?

**Comment by ennerf** [comment]
I tried to fix this, but ran into a library issue https://github.com/GSI-CS-CO/chart-fx/issues/465

**Comment by ennerf** [comment]
Found a way to work around it and switched from 5% relative padding to 10% of the full range. How do you like this?

![image](https://user-images.githubusercontent.com/5491587/134533596-5cb2a34d-2001-439e-a02c-45253dd87045.png)
