### ISSUE TITLE
Be able to toggle between absolute / signed error

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/scope2-feedback#99]
Sometimes you want to view error in signed terms, not just abs value.  Maybe if have it switch if you click the y-axis of the error?  Maybe just an option in "Settings"?  Low-ish priority since you can always just make a custom plot instead :-)

**Comment by ennerf** [comment]
👍 

![image](https://user-images.githubusercontent.com/5491587/134323585-87bbe341-e4a9-4234-9a8b-27bc1bae6aad.png)
